# Generated by Django 5.2 on 2025-05-02 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/uploads/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Упаковка',
                'verbose_name_plural': 'Упаковки',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('color', models.CharField(null=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Статус доставки',
                'verbose_name_plural': 'Статусы доставки',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорты',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер автомобиля')),
                ('departure_time', models.DateTimeField(verbose_name='Время отправки')),
                ('delivery_time', models.DateTimeField(verbose_name='Время доставки')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Дистанция (км)')),
                ('technical_state', models.BooleanField(default=True, verbose_name='Техническое состояние')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель заказа')),
                ('file', models.ManyToManyField(blank=True, related_name='files', to='referential.file', verbose_name='Файл')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referential.packaging', verbose_name='Упаковка')),
                ('services', models.ManyToManyField(to='referential.service', verbose_name='Услуги')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referential.status', verbose_name='Статус')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referential.transport', verbose_name='Модель транспорта')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='referential_status__392ccd_idx'), models.Index(fields=['operator_id'], name='referential_operato_c88617_idx')],
            },
        ),
    ]
