# Generated by Django 5.2 on 2025-05-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referential', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставки'},
        ),
    ]
